package com.protap.iso24817calc.domain

data class B31GDetails(
    val method: String,
    val dOverT: Double,
    val z: Double,
    val foliasM: Double,
    val flowStressMpa: Double,
    val failureStressMpa: Double,
    val failurePressureMpa: Double,
    val safePressureMpa: Double,
    val applicable: Boolean,
    val acceptable: Boolean,
    val warnings: List<String>,
)

data class TypeBDetails(
    val defectSizeUsedMm: Double,
    val designLifeYears: Double,
    val serviceTempLimitC: Double,
    val fLeak: Double,
    val fT2: Double,
    val gammaLclJPerM2: Double,
    val eAcMpa: Double,
    val maxPressureAsymptoteMpa: Double,
    val validityLimitMm: Double,
    val withinValidity: Boolean,
    val repairableFormula12: Boolean,
    val formula12ThicknessMm: Double?,
    val typeAThicknessMm: Double,
)

data class CalculationResult(
    val customer: String,
    val location: String,
    val reportNo: String,
    val odMm: Double,
    val wallMm: Double,
    val yieldStrengthMpa: Double,
    val pressureBar: Double,
    val temperatureC: Double,
    val defectType: String,
    val defectLocation: String,
    val remainingWallMm: Double,
    val remainingWallEolMm: Double,
    val internalCorrosionRateMmPerYear: Double,
    val defectLengthMm: Double,
    val wallLossRatio: Double,
    val calcMethodThickness: String,
    val calcMethodOverlap: String,
    val safetyFactor: Double,
    val temperatureFactor: Double,
    val designStrain: Double,
    val pressureMpa: Double,
    val steelCapacityMpa: Double,
    val compositeDesignPressureMpa: Double,
    val requiredThicknessMm: Double,
    val numPlies: Int,
    val finalThicknessMm: Double,
    val isoLengthMm: Double,
    val overlapLengthMm: Double,
    val geometricOverlapMm: Double,
    val transferOverlapMm: Double,
    val taperLengthMm: Double,
    val numBands: Int,
    val procurementLengthMm: Double,
    val clothWidthMm: Double,
    val optimizedSquareMeters: Double,
    val epoxyKg: Double,
    val isUpgraded: Boolean,
    val thicknessCheckOk: Boolean,
    val warnings: List<String>,
    val b31g: B31GDetails?,
    val typeB: TypeBDetails?,
)
